### ISSUE TITLE
DaggerTestComponent missing

### ISSUE THREAD

**Issue by younes0** [jrobinson3k1/dagger2-demo#1]
In `MainActivityTest.java`, you import `com.jasonrobinson.dagger2demo.dagger.DaggerTestComponent` which doesn't exist

**Comment by jrobinson3k1** [comment]
All Dagger\* classes are generated when you build the project. It searches your project structure for classes annotated with `@Component` and generates a class that you can import and use. Are you having trouble generating this class?

**Comment by younes0** [comment]
Oops, I had renamed the TestComponent class. Everythin's okay now.
Your dagger/test usecase example is by far the easier one that I came across, appreciate that.
